version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.8

jobs:
  build-and-test:
    executor: python-executor
    steps:
      - checkout

      # Run the tests
      - run:
          name: Run tests
          command: python tpy.py

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
